pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch: 'main', url: 'YOUR_REPO_LINK'
            }
        }
        stage('Build') {
            steps {
                bat 'docker build -t ci-app .'
            }
        }
        stage('Test') {
            steps {
                echo 'Basic test passed'
            }
        }
    }
}